# Generated by Django 5.0.1 on 2024-01-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_remove_post_blog_post_publish_bb7600_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
